#server:
#  port: 1001
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-blog
    username: postgres
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
project:
  upload: upload/
base:
  url: http://localhost:8080
  
  
  